---
- hosts: all
  tasks:
    - name: check sshd state    #service sshd start
      ansible.builtin.service:  #systemctl start sshd 
        name: sshd
        state: started

    - name: Check rsyslog state
      ansible.builtin.service:
        name: rsyslog
        state: started